language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t gudrlf789/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true gudrlf789/react-test-app npm run test

after_success:
  - docker build -t gudrlf789/docker-frontend ./frontend
  - docker build -t gudrlf789/docker-backend ./backend
  - docker build -t gudrlf789/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push gudrlf789/docker-frontend
  - docker push gudrlf789/docker-backend
  - docker push gudrlf789/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "어플리케이션 이름"
  env: "환경 이름"
  bucket_name: S3 버킷 이름
  bucket_path: "application 이름과 동일"
  on:
    branch: master
